language: rust

branches:
  except:
    - /^v\d+\.\d+\.\d+$/ # Exclude tags in the style of v1.2.3

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - { os: linux, rust: 1.36.0   }
    - { os: linux, rust: stable   }
    - { os: linux, rust: beta     }
    - { os: linux, rust: nightly  }

script:
  - cargo test --all

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - unzip
